test(unit test dispenser): test the cycle of a working dispenser.
ES-EDU-SIEGMA/Embedded-Controller pull request #70
Opened 2024-01-08 21:02 UTC by YULEMING

2024-01-08 21:03 UTC, YULEMING commented
#58 completed the unit test on dispenser.

2024-01-09 12:04 UTC, DavidFederl requested changes

2024-01-09 12:04 UTC, DavidFederl commented on test/unit/CMakeLists.txt
`.h` files should be added to the `add_executable` block. Inside this block should only be `.c` files which provide executed source code.

2024-01-09 17:13 UTC, DavidFederl approved these changes

2024-01-09 17:13 UTC, merged